name: noticeboard
description: "A serverless talking noticeboard."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  auto_size_text: ^3.0.0
  backstreets_widgets: ^0.37.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.49.1
  flutter_soloud: ^3.3.3
  flutter_tts: ^4.2.3
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
  assets:
    - sounds/
