name: noticeboard
description: "A talking noticeboard."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  auto_size_text: ^3.0.0
  backstreets_widgets: ^0.16.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.28.0
  flutter_soloud: ^2.1.3
  path: ^1.9.0
  path_provider: ^2.1.4
  serverpod_flutter: 2.1.1
  talking_noticeboard_client:
    path: ../talking_noticeboard_client

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - sounds/
