name: noticeboard
description: "A serverless talking noticeboard."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_size_text: ^3.0.0
  backstreets_widgets: ^0.35.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.48.3
  flutter_soloud: ^3.2.2
  flutter_tts: ^3.8.5
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.5
  window_manager: ^0.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - sounds/
